### Data Science and Machine Learning Cheatsheet
&nbsp; 
##### I am a data scientist and machine learning engineer with a decade of experience applying statistical learning, artificial intelligence, and software engineering to political, social, and humanitarian efforts -- from election monitoring to disaster relief. I work at Devoted Health, using data science and machine learning to help fix America's health care system.
&nbsp;
##### Learning machine learning? Check out my Machine Learning Flashcards or my book, Machine Learning With Python Cookbook.
&nbsp;
### Machine Learning

#### Vectors, Matrices, Arrays


##### 1. Transpose a vector or a matrix

In [3]:
# load library
import numpy as np

In [4]:
# create a vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [5]:
# create a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
# transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

##### 2. Selecting an element from a vector,matrix

In [7]:
# selecting an element from a vector
vector[0]

1

In [8]:
# selecting an element from a matrix
matrix[0,1]

2

In [9]:
# Create tensor
tensor = np.array([
                    [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]]
                  ])

In [10]:
# Select second element of each of the three dimensions
tensor[1,1,1]

array([4, 4])

##### 3.Reshape an array

In [11]:
# Reshape matrix into 1x9 matrix
matrix.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

##### 4. Invert a matrix

In [12]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

In [13]:
# calculating an inverse of a matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

##### 5. Getting diagonal of a matrix

In [14]:
# Return diagonal elements
matrix.diagonal()

array([1, 5])

In [15]:
# Return the trace
matrix.diagonal().sum()

6

##### 6. Flatten a matrix 

In [16]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) 

In [17]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 7. Finding the rank of the matrix

In [18]:
np.linalg.matrix_rank(matrix)

2

##### 8. Finding the max and min of matrix

In [19]:
# getting the maximum of the matrix
np.max(matrix)

9

In [20]:
# getting the minimum of the matrix
np.min(matrix)

1

##### 9. Describing a matrix

In [21]:
# View number of rows and columns
matrix.shape

(3, 3)

In [22]:
# View number of elements (rows * columns)
matrix.size

9

In [23]:
# View number of dimensions
matrix.ndim

2

##### 10. Create a row vector and column vector

In [24]:
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [25]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_column

array([[1],
       [2],
       [3]])

##### 11. Creating a sparse matrix

In [26]:
# importing library
from scipy import sparse

In [27]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
matrix_sparse

<3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

##### 12. Converting a dictionary into matrix

In [29]:
# Load library
from sklearn.feature_extraction import DictVectorizer

In [30]:
# Our dictionary of data
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

In [31]:
# Create DictVectorizer object
dictvectorizer = DictVectorizer(sparse=False)

# Convert dictionary into feature matrix
features = dictvectorizer.fit_transform(data_dict)

# View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [32]:
# View feature matrix column names
dictvectorizer.get_feature_names()

['Blue', 'Red', 'Yellow']

##### 13. Calculate the determinant

In [36]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [37]:
# Return determinant of matrix
np.linalg.det(matrix)

0.0

In [38]:
##### 14. Calculate mean, variance, standard deviation

In [39]:
# Return mean
np.mean(matrix)

5.0

In [40]:
# Return variance
np.var(matrix)

6.666666666666667

In [41]:
# Return standard deviation
np.std(matrix)

2.581988897471611

##### 15. Calculate dot product of two vectors

In [42]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [43]:
# Calculate dot product
np.dot(vector_a, vector_b)

32

##### 16. Apply operations on matrix

In [46]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [47]:
# Create a function that adds 100 to something
add_100 = lambda i: i + 100

# Create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [48]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])